name: "Validate renovate.json config file"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-user-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: konflux-ci/renovate-config-validator-action@main
        with:
          config_file: .github/renovate.json

  validate-backend-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: konflux-ci/renovate-config-validator-action@main
        with:
          config_file: config/renovate/renovate.json
